materias = [
    "Lenguajes y automatas I",
    "Lenguajes y Automatas II",
    "Programación Lógica y Funcional",
    "Inteligencia Artificial",
    "Cálculo Diferencial",
    "Cálculo Integral",
    "Cálculo Vectorial",
    "Ecuaciones Diferenciales",
    "Graficación",
    "Programación Web",
    "Ingeniería de Software",
    "Fundamentos de Ingeniería de Software",
    "Taller de Base de Datos",
    "Sistemas Operativos",
    "Fundamentos de Telecomunicaciones",
    "Redes de Computadoras",
    "Taller de Sistemas Operativos",
    "Métodos Numéricos",
    "Tópicos Avanzados de Programación",
    "Taller de Administración",
    "Fundamentos de Investigación",
    "Algebra Lineal",
    "Probabilidad y Estadística",
    "Principios Eléctricos y Aplicaciones Digitales",
    "Simulación",
    "Fundamentos de Programación",
    "Residencia Profesional",
    "Servicio Social",
    "Gestión de Proyectos de Software",
    "Taller de Investigación I",
    "Administración de Redes",
    "Conmutación y Enrutamiento en Redes de Datos",
    "Taller de Investigación II",
    "Programacion Orientada a Objetos",
    "Taller de Ética",
    "Matemáticas Discretas",
    "Investigación de Operaciones",
    "Fundamentos de Base de Datos",
    "Lenguajes de Interfaz",
    "Arquitectura de Computadoras",
    "Sistemas Programables",
    "Programación Web",
    "Física General",
    "Administración de Base de Datos",
    "Desarrollo Sustentable",
    "Cultura Empresarial",
    "Contabilidad Financiera",
    "Química",
    "Estructura de Datos"
]